server:
  port: 8761

spring:
  application:
    name: service-registry

  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/
    register-with-eureka: false
    fetch-registry: false