
version: "3"

services:
  postgres:
    image: postgres:9.6
    container_name: "microservice-customer"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - TZ=GMT
    volumes:
      - "./data/postgres:/var/lib/postgres/data"
    ports:
      - 5432:5432
    networks:
      - postgres
  zipkin:
    image: openzipkin/zipkin-slim
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mem
    ports:
      - 9411:9411
    depends_on:
      - storage
    networks:
      - spring

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ".data/rabbitmq:/var/lib/rabbitmq/data"
    networks:
      - rabbitmq_java_net

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
    external: false
  rabbitmq_java_net:
    driver: bridge
